language     = "en-us"
baseurl      = "https://irkode.github.io/highlightjs-hugo"
title        = "Highlight 4 Hugo"
disableKinds = ['rss', 'sitemap', 'taxonomy', 'term']

# for our json and js files
uglyUrls = 'true'

# for github README and LICENSE files
disablePathToLower = true

[params]
   subTitle   = "Advanced syntax highlighting for Hugo templates"
   author     = "Irkode <irkode@rikode.de>"
   webRoot    = "https://irkode.github.io/highlightjs-hugo"
   repoRoot   = "https://github.com/irkode/"
   repository = "https://github.com/irkode/highlightjs-hugo"
   releases   = "https://github.com/irkode/highlightjs-hugo/releases/latest"
   blobs      = "https://github.com/irkode/highlightjs-hugo/blob/main"
   category   = "templates"
   license    = "MIT"
   licenseURL = "https://github.com/irkode/highlightjs-hugo/blob/main/LICENSE"

# we generate javascript files for the data structures needed by plugins
[outputFormats.js]
   isHTML         = false
   isPlainText    = true
   mediaType      = "text/javascript"
   notAlternative = true
   ugly           = true

# generate keywords.yaml (human-readable dump of the same keyword map used for keywords.js)
[outputFormats.yaml]
   isHTML         = false
   isPlainText    = true
   mediaType      = "application/yaml"
   notAlternative = true
   ugly           = true

[module]
   # make sure we do not loose our own files
   [[module.mounts]]
      source = 'assets'
      target = 'assets'
   [[module.mounts]]
      source = "../_assets"
      target = "assets"
   [[module.mounts]]
      source = '../../LICENSE'
      target = 'assets/content/LICENSE'
   [[module.mounts]]
      source = "../_snippets/hugo-css-class-reference.md"
      target = "assets/content/css-class-reference.md"

   [[module.mounts]]
      source = 'content'
      target = 'content'
   [[module.mounts]]
      source = "../_snippets"
      target = "content/_snippets"
   [[module.mounts]]
      source = "../../README.md"
      target = "content/_snippets/README.md"

   # import function part of the documentation
   [[module.imports]]
      ignoreConfig  = true
      ignoreImports = true
      path          = 'github.com/gohugoio/hugoDocs'
      version       = 'master'
      [[module.imports.mounts]]
         source = "content/en/functions"
         target = "content/functions"
      # these are referenced even if a page is not rendered
      [[module.imports.mounts]]
         source = "layouts/_shortcodes"
         target = "layouts/functions/_shortcodes"

   [module.hugoVersion]
      min = '0.164.0'
