baseURL = "https://irkode.github.io/highlightjs-hugo/"
locale  = 'en-US'
title   = "Highlight 4 Hugo"

description   = "Advanced syntax highlighting for Hugo templates"
disableKinds  = ['rss', 'sitemap', 'taxonomy', 'term']
enableGitInfo = true
theme         = "huggingface"

[build]
   noJSConfigInAssets = true
   [build.buildStats]
      enable = false
   [[build.cachebusters]]
      source = 'DISABLED'
      target = 'DISABLED'
[markup]
   [markup.highlight]
      noClasses = false
      lineNos   = false
   [markup.goldmark.renderHooks.image]
      useEmbedded = "always"
   [markup.goldmark.renderHooks.link]
      useEmbedded = "always"

[module]
   [[module.mounts]]
      source = "assets"
      target = "assets"
   [[module.mounts]]
      source = "../../release/highlight-hugo.min.js"
      target = "assets/js/highlight-hugo.min.js"
   [[module.mounts]]
      source = "content"
      target = "content"
   [[module.mounts]]
      source = "../_snippets"
      target = "content/_snippets"
   [[module.mounts]]
      source = "../../README.md"
      target = "content/_snippets/README.md"
   [[module.mounts]]
      source = "../../LICENSE"
      target = "content/_snippets/license.md"
   [[module.mounts]]
      source = "../../highlightjs-hugo.png"
      target = "static/highlightjs-hugo.png"

   [module.hugoVersion]
      extended = false
      min      = '0.161.1'
