language     = "en-us"
baseurl      = "https://irkode.github.io/highlightjs-hugo"
title        = "Highlight 4 Hugo"
disableKinds = ['rss', 'sitemap', 'taxonomy', 'term']

[mediaTypes.'text/x-discourse-gjs']
   suffixes = ['gjs']

[outputFormats.json]
   baseName    = 'about'
   isPlainText = true

[outputFormats.gjs]
   mediaType      = 'text/x-discourse-gjs'
   baseName       = 'javascripts/discourse/api-initializers/theme-initializer'
   isHTML         = false
   isPlainText    = true
   notAlternative = true

[build]
   noJSConfigInAssets = true

[params]
   subTitle   = "Advanced syntax highlighting for Hugo templates"
   author     = "Irkode <irkode@rikode.de>"
   webRoot    = "https://irkode.github.io/highlightjs-hugo"
   repoRoot   = "https://github.com/irkode/"
   repository = "https://github.com/irkode/highlightjs-hugo"
   releases   = "https://github.com/irkode/highlightjs-hugo/releases/latest"
   blobs      = "https://github.com/irkode/highlightjs-hugo/blob/main"
   category   = "templates"
   license    = "MIT"
   licenseURL = "https://github.com/irkode/highlightjs-hugo/blob/main/LICENSE"

[module]
   [[module.mounts]]
      source = '../../release/highlightjs/'
      target = 'assets/highlightjs/'
      files  = ["! **embed**", "**/dist/*.es.min.js"]
   [[module.mounts]]
      source = "../../LICENSE"
      target = "static/go-html/LICENSE"
   [[module.mounts]]
      source = "../../LICENSE"
      target = "static/go-text/LICENSE"
   [[module.mounts]]
      source = "../../LICENSE"
      target = "static/hugo-html/LICENSE"
   [[module.mounts]]
      source = "../../LICENSE"
      target = "static/hugo-text/LICENSE"

   [module.hugoVersion]
      min = '0.164.0'
