language     = "en-us"
baseurl      = "https://irkode.github.io/highlightjs-hugo"
title        = "Highlight 4 Hugo"
disableKinds = ['rss', 'sitemap', 'taxonomy', 'term']

[params]
   subTitle   = "Advanced syntax highlighting for Hugo templates"
   author     = "Irkode <irkode@rikode.de>"
   webRoot    = "https://irkode.github.io/highlightjs-hugo"
   repoRoot   = "https://github.com/irkode/"
   repository = "https://github.com/irkode/highlightjs-hugo"
   releases   = "https://github.com/irkode/highlightjs-hugo/releases/latest"
   blobs      = "https://github.com/irkode/highlightjs-hugo/blob/main"
   category   = "templates"
   license    = "MIT"
   licenseURL = "https://github.com/irkode/highlightjs-hugo/blob/main/LICENSE"

[module]
   [[module.mounts]]
      source = 'assets'
      target = 'assets'

   [[module.mounts]]
      source = '../../release/highlightjs/'
      target = 'assets/highlightjs/'
      files  = ["! **/dist/*.es.min*.js", "! **embed**", "**/dist/*min*.js"]
   [[module.mounts]]
      source = "../../LICENSE"
      target = "assets/discourse/LICENSE"

   [module.hugoVersion]
      extended = true
      min      = '0.161.1'
