language     = "en-us"
baseurl      = "https://irkode.github.io/highlightjs-hugo"
title        = "Highlight 4 Hugo"
disableKinds = ['rss', 'sitemap', 'taxonomy', 'term']

[params]
   subTitle   = "Advanced syntax highlighting for Hugo templates"
   author     = "Irkode <irkode@rikode.de>"
   webroot    = "https://irkode.github.io/highlightjs-hugo"
   reporoot   = "https://github.com/irkode/"
   repository = "https://github.com/irkode/highlightjs-hugo"
   releases   = "https://github.com/irkode/highlightjs-hugo/releases/latest"
   blobs      = "https://github.com/irkode/highlightjs-hugo/blob/main"
   category   = "templates"
   license    = "MIT"
   licstart   = 2026
   licenseURL = "https://github.com/irkode/highlightjs-hugo/blob/main/LICENSE"

# mount results of Highlight.js build to assets
[module]
   [[module.mounts]]
      source = 'assets'
      target = 'assets'

   [[module.mounts]]
      source = '../../release/highlightjs/'
      target = 'assets/highlightjs/'
      files  = ["! **/dist/*.es.min*.js", "! **embed**", "**/dist/*min*.js"]

   [module.hugoVersion]
      extended = true
      min      = '0.161.1'
