# top level entries
[[main]]
   name    = 'Discourse'
   pageRef = '/discourse'
   weight  = 10
[[main]]
   name   = 'Highlight.js'
   weight = 20
[[main]]
   name   = 'Hugo'
   weight = 30

# submenu Highlight.js
[[main]]
   identifier = 'Highlightjs_Overview'
   name       = 'Overview'
   pageRef    = '/highlightjs'
   Parent     = "Highlight.js"
   weight     = 1
[[main]]
   name    = 'Hugo-Html'
   pageRef = '/highlightjs/hugo-html'
   Parent  = "Highlight.js"
   weight  = 10
[[main]]
   name    = 'Hugo-Text'
   pageRef = '/highlightjs/hugo-text'
   Parent  = "Highlight.js"
   weight  = 20
[[main]]
   name    = 'CSS Classes'
   pageRef = '/highlightjs/hugo-css-class-reference'
   Parent  = "Highlight.js"
   weight  = 30

# submenu Highlight.js
[[main]]
   identifier = 'Hugo_Overview'
   name       = 'Overview'
   pageRef    = '/hugo'
   Parent     = "Hugo"
   weight     = 1
