baseURL      = "https://irkode.github.com/highlightjs-hugo/"
languageCode = 'en-US'
title        = "Highlight 4 Hugo - Advanced syntax highlighting for Hugo templates"
disableKinds = ['rss', 'sitemap', 'taxonomy', 'term']
theme        = "huggingface"

[module]
  [[module.mounts]]
    source = "../README.md"
    target = "content/_index.md"
  [[module.mounts]]
    source = ".."
    target = "content"
    files  = ['*.png']
