# coded with friendly help from https://duckduckgo.com/?q=DuckDuckGo+AI+Chat&ia=chat&duckai=1
name: Build Highlight.js with extras (fully cached)

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-highlightjs:
    runs-on: ubuntu-latest

    steps:
      # --- Setup Node.js 22
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # --- Cache the cloned Highlight.js repo
      - name: Cache Highlight.js clone
        id: cache-hljs
        uses: actions/cache@v4
        with:
          path: highlight.js
          key: highlightjs-11.11.1

      # --- Clone Highlight.js only if cache missed
      - name: Clone Highlight.js
        if: steps.cache-hljs.outputs.cache-hit != 'true'
        run: |
          git clone --branch 11.11.1 --depth 1 https://github.com/highlightjs/highlight.js.git
          rm -Rf highlight.js/extra

      # --- Cache node_modules from npm ci (depends on package-lock + version)
      - name: Cache node_modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: highlight.js/node_modules
          key: npm-11.11.1-${{ hashFiles('highlight.js/package-lock.json') }}

      # --- Checkout your own repo (highlightjs-hugo)
      - name: Checkout highlightjs-hugo repository
        uses: actions/checkout@v4
        with:
          path: highlight.js/extra

      # --- Install and build (npm ci skipped if node_modules restored)
      - name: Install dependencies and build
        working-directory: highlight.js
        run: |
          if [ ! -d "node_modules" ] || [ -z "$(ls -A node_modules)" ]; then
            echo "Running npm ci..."
            npm ci
          else
            echo "Using cached node_modules."
          fi
          npm run build

      - name: Execute markup tests
        working-directory: highlight.js
        run: |
          npm run test-markup

      - name: Create Distribution files
        working-directory: highlight.js
        run: |
          node ./tools/build.js hugo hugo-text -t cdn
          tree extra

      # - name: Compare distribution outputs
      #   run: |
      #     echo "Comparing built dist files with source dist files..."
      #     diff -qr highlight.js/extra/highlightjs-hugo/dist highlightjs-hugo/dist || (
      #       echo "::error::Distribution files differ!"
      #       exit 1
      #     )
