# coded with friendly help from https://duckduckgo.com/?q=DuckDuckGo+AI+Chat&ia=chat&duckai=1
name: Build Highlight.js with extras (fully cached)

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-highlightjs:
    runs-on: ubuntu-latest

    env:
      ONLY_EXTRA: "true"
      GO_VERSION: 1.25.1
      HUGO_VERSION: 0.151.0
    steps:
      # --- Setup Node.js 22
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install Hugo
        run: |
          curl -sLJO "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz"
          mkdir "${HOME}/.local/hugo"
          tar -C "${HOME}/.local/hugo" -xf "hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz"
          rm "hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz"
          echo "${HOME}/.local/hugo" >> "${GITHUB_PATH}"

      - name: Verify installations
        run: |
          echo "Go: $(go version)"
          echo "Hugo: $(hugo version)"
          echo "Node.js: $(node --version)"

      # --- Cache the cloned Highlight.js repo
      - name: Cache Highlight.js clone
        id: cache-hljs
        uses: actions/cache@v4
        with:
          path: highlight.js
          key: highlightjs-11.11.1

      # --- Clone Highlight.js only if cache missed
      - name: Clone Highlight.js
        if: steps.cache-hljs.outputs.cache-hit != 'true'
        run: |
          git clone --branch 11.11.1 --depth 1 https://github.com/highlightjs/highlight.js.git
          rm -Rf highlight.js/extra

      # --- Cache node_modules from npm ci (depends on package-lock + version)
      - name: Cache node_modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: highlight.js/node_modules
          key: npm-11.11.1-${{ hashFiles('highlight.js/package-lock.json') }}

      # --- Checkout your own repo (highlightjs-hugo)
      - name: Checkout highlightjs-hugo repository
        uses: actions/checkout@v4
        with:
          path: highlight.js/extra

      - name: run Hugo
        working-directory: path: scripts/hugen
        run: |
          hugo -d highlight.js/extra

      # --- Install and build (npm ci skipped if node_modules restored)
      - name: Install dependencies and build
        working-directory: highlight.js
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: |
          echo "Running npm ci..."
          npm install --save-dev

      - name: Run Highlight.js build
        working-directory: highlight.js
        run: |
          npm run build

      - name: Execute markup tests
        working-directory: highlight.js
        run: |
          npm run test-markup

      - name: Create Distribution files
        working-directory: highlight.js
        run: |
          node ./tools/build.js hugo hugo-text -t cdn
          tree extra

      # - name: Compare distribution outputs
      #   run: |
      #     echo "Comparing built dist files with source dist files..."
      #     diff -qr highlight.js/extra/highlightjs-hugo/dist highlightjs-hugo/dist || (
      #       echo "::error::Distribution files differ!"
      #       exit 1
      #     )
